#!/bin/bash
# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    bounce                                            :+:      :-:     :+:    #
#                                                     +:+ +:+         +:++    #
#    By: pibouill <pibouill@student.42prague.com>   +#++:++#++:++#+:++#++:    #
#                                                 +#++:++#++:++:++:++:++:++    #
#    Created: 2026/05/04 12:00:00 by pibouill          #+#    #+#            #
#    Updated: 2026/05/04 12:00:00 by pibouill         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

clear
pos=0
dir=1
while true; do
    printf "\r%${pos}sO" | tr ' ' ' '
    pos=$((pos + dir))
    if [ $pos -ge 100 ] || [ $pos -le 0 ]; then
        dir=$((dir * -1))
    fi
    sleep 0.1
done
