#!/bin/bash
# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    matrix                                             :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: pibouill <pibouill@student.42prague.com>   +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2026/05/14 11:03:24 by pibouill          #+#    #+#              #
#    Updated: 2026/05/14 11:03:24 by pibouill         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

while true; do
    echo -ne "\033[2J\033[H"
    for i in {1..20}; do
        tr -dc 'a-zA-Z0-9!@#$%^&*()' </dev/urandom | head -c 80
        echo
    done
    sleep 0.1
done
