#!/bin/bash
# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    random_json                                     :+:+: :+:+:  +:++:+     #
#                                                     :+:+:+: :+:+:+  +:++    #
#    By: pibouill <pibouill@student.42prague.com>   +:++#++:+#++#++:++#++:++  #
#                                                 +:++#++:+#++#++:++#++:++:++#
#    Created: 2026/05/04 12:00:00 by pibouill          #+#    #+#            #
#    Updated: 2026/05/04 12:00:00 by pibouill         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

clear
echo "Searching the web for answers..."
while true; do
    curl -s --max-time 2 "https://jsonplaceholder.typicode.com/posts/$(shuf -i 1-100 -n 1)" 2>/dev/null | head -c 80
    echo ""
    sleep 2
done
